# -*- coding: utf-8 -*-
"""YoloV3Sample.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LbKkQf4hbIuiUHunLlvY-cc0d_sNcAgS
"""

#!git clone https://github.com/theschoolofai/YoloV3.git

from google.colab import drive
drive.mount('/content/gdrive')

cd '/content/gdrive/MyDrive/YoloV3'

import time
import glob
import torch
import os

from IPython.display import Image, clear_output 
print('PyTorch %s %s' % (torch.__version__, torch.cuda.get_device_properties(0) if torch.cuda.is_available() else 'CPU'))



!ls

!ls

!python train.py --data data/smalcoco/smalcoco.data --batch 3 --cache --epochs 3 --nosave

#!python train.py --data /content/gdrive/MyDrive/YoloV3/data/assignment13/custom.data --batch 10 --cache --cfg /content/gdrive/MyDrive/YoloV3/cfg/yolov3-custom.cfg --epochs 10 --nosave
!python train.py --data /content/gdrive/MyDrive/YoloV3/data/assignment13/custom.data --batch 10 --cache --cfg cfg/yolov3-custom.cfg --epochs 3 --nosave

!python detect.py --conf-thres 0.1 --output out_out

Image(filename='out_out/ezgif-frame-001.jpg', width=600)

Image(filename='out_out/ezgif-frame-100.jpg', width=600)

Image(filename='out_out/ezgif-frame-092.jpg', width=600)

Image(filename='out_out/ezgif-frame-063.jpg', width=600)

